insert into MEMBER (MEMBER_ID, PWD, ROLE_GROUP) values ('adv', '$2a$12$MgEeHQnarEOaP4YmxICz1eGp2BRkdvFirHVHGmAaWIDR4hKiItVum', 'ROLE_ADV');
insert into MEMBER (MEMBER_ID, PWD, ROLE_GROUP) values ('admin', '$2a$12$5gAfweaYifUjut.wYjcghef9bkAUiccQaLkU6O3dUWlcmRnK.Hue.', 'ROLE_ADMIN');

insert into ADV (ADV_ID, AD_ING_ACT_YN, BALANCE, EVENT_MONEY, DAY_LIMIT_BUDGET) values ('adv', 1, 1000000, 0, 0);

insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB01', '상품상품01', 1, 1000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB02', '상품상품02', 0, 2000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB03', '상품상품03', 1, 3000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB04', '상품상품04', 0, 4000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('OBS_DB01', '상품상품05', 1, 5000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('OBS_DB02', '상품상품06', 0, 6000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('OBS_DB03', '상품상품07', 1, 7000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('OBS_DB04', '상품상품08', 0, 8000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('PBS_DB01', '상품상품09', 1, 9000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('PBS_DB02', '상품상품10', 0, 10000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('PBS_DB03', '상품상품11', 1, 11000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('PBS_DB04', '상품상품12', 0, 12000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('QBS_DB01', '상품상품13', 1, 13000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('QBS_DB02', '상품상품14', 0, 14000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('QBS_DB03', '상품상품15', 1, 15000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('QBS_DB04', '상품상품16', 0, 16000, 0);

insert into AGROUP(AGROUP_NAME, REG_TIME, AGROUP_ACT_YN, AGROUP_USE_CONFIG_YN) values('광고그룹01', CURRENT_TIMESTAMP, 1, 1);
insert into AGROUP(AGROUP_NAME, REG_TIME, AGROUP_ACT_YN, AGROUP_USE_CONFIG_YN) values('광고그룹02', CURRENT_TIMESTAMP, 1, 1);