insert into MEMBER (MEMBER_ID, PWD, ROLE_GROUP) values ('adv', '$2a$12$MgEeHQnarEOaP4YmxICz1eGp2BRkdvFirHVHGmAaWIDR4hKiItVum', 'ROLE_ADV');
insert into MEMBER (MEMBER_ID, PWD, ROLE_GROUP) values ('admin', '$2a$12$5gAfweaYifUjut.wYjcghef9bkAUiccQaLkU6O3dUWlcmRnK.Hue.', 'ROLE_ADMIN');

insert into ADV (ADV_ID, AD_ING_ACT_YN, BALANCE, EVENT_MONEY, DAY_LIMIT_BUDGET) values ('adv', 1, 1000000, 0, 0);

insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB01', '상품상품01', 1, 10000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB02', '상품상품02', 0, 5000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB03', '상품상품03', 1, 4000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB04', '상품상품04', 0, 3000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB05', '상품상품05', 0, 100, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB06', '상품상품06', 1, 200, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB07', '상품상품07', 0, 300, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB08', '상품상품08', 1, 400, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB09', '상품상품09', 1, 500, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB10', '상품상품10', 1, 60000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB11', '상품상품11', 0, 10000, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB12', '상품상품12', 0, 60000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB13', '상품상품13', 1, 60000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB14', '상품상품14', 0, 60000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB15', '상품상품15', 0, 60000, 0);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB16', '상품상품16', 1, 300, 1);
insert into ITEM(ITEM_NO, ITEM_NAME, ADULT_YN, ITEM_ORG_COST, ITEM_ACT_YN) values('NBS_DB17', '상품상품17', 0, 300, 1);

insert into AGROUP(AGROUP_NAME, REG_TIME, AGROUP_ACT_YN, AGROUP_USE_CONFIG_YN) values('광고그룹01', CURRENT_TIMESTAMP, 1, 1);
insert into AGROUP(AGROUP_NAME, REG_TIME, AGROUP_ACT_YN, AGROUP_USE_CONFIG_YN) values('광고그룹02', CURRENT_TIMESTAMP, 1, 1);